(function() {var implementors = {};
implementors['portaudio'] = ["<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='portaudio/stream/enum.StreamCallbackResult.html' title='portaudio::stream::StreamCallbackResult'>StreamCallbackResult</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamTimeInfo.html' title='portaudio::stream::StreamTimeInfo'>StreamTimeInfo</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamCallbackFlags.html' title='portaudio::stream::StreamCallbackFlags'>StreamCallbackFlags</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamFlags.html' title='portaudio::stream::StreamFlags'>StreamFlags</a>","<a class='stability Experimental' title='Experimental'></a>impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamParameters.html' title='portaudio::stream::StreamParameters'>StreamParameters</a>&lt;T&gt;","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamInfo.html' title='portaudio::stream::StreamInfo'>StreamInfo</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='portaudio/pa/enum.PaError.html' title='portaudio::pa::PaError'>PaError</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='portaudio/hostapi/enum.HostApiType.html' title='portaudio::hostapi::HostApiType'>HostApiType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
